### ISSUE TITLE
在阿里云机器上启动报错了

### ISSUE THREAD

**Issue by bluesky0521** [huahua132/skynet_fly#13]
之前在腾讯云上传启动没问题，今天换了一台阿里云的机器就报这样的错误了，环境搭建都是一样的步骤，这是为啥啊
> [:0000000d][20231128 13:26:21 23][fatal][contriner_mgr][../../skynet_fly/service/contriner_mgr.lua:81]launch_new_module err  room_game_hall_m {
>     net_util = ws_pbnet_util,
>     hall_plug = hall_plug,
> }
> 
> [:00000011][20231128 13:26:21 23]LAUNCH snlua hot_container room_game_alloc_m 1 2023-11-28[13:26:21] 1701149181 1
> [:00000010][20231128 13:26:21 23]lua call [d to :10 : 6 msgsz = 51] error : ^[[31m../../skynet_fly/skynet/lualib/skynet.lua:966: ../../skynet_fly/skynet/lualib/skynet.lua:434: ../../skynet_fly/skynet/lualib/skynet/require.lua:96: ../../skynet_fly/skynet/lualib/skynet/require.lua:96: ../../skynet_fly/skynet/lualib/skynet/require.lua:96: ../../skynet_fly/skynet/lualib/skynet/require.lua:96: ../../skynet_fly/skynet/lualib/skynet.lua:53: assertion failed!
> stack traceback:
>     [C]: in function 'assert'
>     ../../skynet_fly/skynet/lualib/skynet.lua:53: in function 'skynet.register_protocol'
>     ../../skynet_fly/skynet/lualib/skynet/socket.lua:201: in upvalue 'modfunc'
>     ../../skynet_fly/skynet/lualib/skynet/require.lua:67: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:66>
>     [C]: in function 'xpcall'
>     ../../skynet_fly/skynet/lualib/skynet/require.lua:80: in function 'skynet.require.require'
>     (...tail calls...)
>     ../../skynet_fly/lualib/utils/net/util_net_base.lua:2: in upvalue 'modfunc'
>     ../../skynet_fly/skynet/lualib/skynet/require.lua:67: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:66>
>     [C]: in function 'xpcall'
>     ../../skynet_fly/skynet/lualib/skynet/require.lua:80: in function 'skynet.require.require'
>     (...tail calls...)
>     ../../skynet_fly/lualib/utils/net/ws_pbnet_util.lua:3: in upvalue 'modfunc'
>     ../../skynet_fly/skynet/lualib/skynet/require.lua:67: in function <../../skynet_fly/s

**Comment by huahua132** [comment]
assert(proto[name] == nil and proto[id] == nil)
像是重复注册了socket消息处理

**Comment by huahua132** [comment]
你有重写require么？

**Comment by huahua132** [comment]
![image](https://github.com/huahua132/skynet_fly/assets/41766775/8180fc57-4c84-4896-be6d-08f749e4a2d6)
估计是加载两次socket导致的

**Comment by huahua132** [comment]
201行到53行出错了

**Comment by huahua132** [comment]
估计跟新机无关，可能是旧机代码或者新机代码没有完全一致

**Comment by bluesky0521** [comment]
没有重写，同样的文件夹刚刚上传到腾讯云那个机器上，能跑起来

**Comment by bluesky0521** [comment]
我试一下在新机git拉取再重新编译看看

**Comment by huahua132** [comment]
你可以打印log  看看，是被哪个地方注册了

**Comment by bluesky0521** [comment]
我去看看 ，怀疑是运维那边搞了什么占用了

**Comment by huahua132** [comment]
估计是socket.lua这个文件被加载2次了,正常require只会加载一次

**Comment by huahua132** [comment]
![image](https://github.com/huahua132/skynet_fly/assets/41766775/c46e5064-5aca-453b-bc63-a3151f9cdcd8)
你可以在上方加个日志打印确认问题

**Comment by bluesky0521** [comment]
> [:00000010][20231128 14:10:53 94]skynet.register_protocol...
> [:00000010][20231128 14:10:53 95]skynet.register_protocol...


果然是注册了两次

**Comment by huahua132** [comment]
我暂时不清楚为啥你的环境会加载两次，你可以关注一下require “socket”的地方

**Comment by bluesky0521** [comment]
试了几台机器，腾讯云的能跑起来，阿里云的不行，
可能是安装源不同导致的，我再研究一下。

**Comment by huahua132** [comment]
会不会是阿里云的gcc有问题

**Comment by huahua132** [comment]
![image](https://github.com/huahua132/skynet_fly/assets/41766775/30ffd80b-7302-4090-825a-48adf1a27d53)
你可以在这里加个打印看看

**Comment by huahua132** [comment]
![image](https://github.com/huahua132/skynet_fly/assets/41766775/7464acbc-3058-4113-97aa-370c25ea670f)
注释一下这里

**Comment by huahua132** [comment]
你说一下 系统版本，gcc版本，我有空去试一下，估计是lua require的缓存没有生效

**Comment by bluesky0521** [comment]
加了日志打印的信息：
> [:0000000f][20231128 18:18:07 74]preready write: share_config_m.required
> 1111111111111111 name:	skynet.socket	 m:	table: 0x7f9214400ac0	
> 
> 1111111111111111 name:	skynet.socketdriver	 m:	table: 0x7f9214400a80	
> 
> [:00000010][20231128 18:18:07 76]skynet.register_protocol...
> [:00000010][20231128 18:18:07 76]register_protocol:socket id:6
> [:00000010][20231128 18:18:07 76]skynet.register_protocol...
> [:00000010][20231128 18:18:07 76]register_protocol:socket id:6
> [:00000010][20231128 18:18:07 76]lua call [d to :10 : 6 msgsz = 51] error : ../../skynet_fly/skynet/lualib/skynet.lua:967: ../../skynet_fly/skynet/lualib/skynet.lua:435: ../../skynet_fly/skynet/lualib/skynet/require.lua:99: ../../skynet_fly/skynet/lualib/skynet/require.lua:99: ../../skynet_fly/skynet/lualib/skynet/require.lua:99: ../../skynet_fly/skynet/lualib/skynet/require.lua:99: ../../skynet_fly/skynet/lualib/skynet.lua:54: assertion failed!
> stack traceback:
> 	[C]: in function 'assert'
> 	../../skynet_fly/skynet/lualib/skynet.lua:54: in function 'skynet.register_protocol'
> 	../../skynet_fly/skynet/lualib/skynet/socket.lua:218: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	../../skynet_fly/lualib/utils/net/util_net_base.lua:2: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	../../skynet_fly/lualib/utils/net/ws_pbnet_util.lua:3: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.//lualib/hall/hall_plug.lua:54: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.../skynet_fly/lualib/module/room_game/room_game_hall_m.lua:451: in upvalue 'module_start'
> 	../../skynet_fly/service/hot_container.lua:110: in function 'room_game_hall_m.start'
> 	../../skynet_fly/lualib/utils/skynet_util.lua:40: in upvalue 'f'
> 	../../skynet_fly/skynet/lualib/skynet.lua:385: in function <../../skynet_fly/skynet/lualib/skynet.lua:357>
> stack traceback:
> 	[C]: in function 'error'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:99: in function 'skynet.require.require'
> 	(...tail calls...)
> 	../../skynet_fly/lualib/utils/net/util_net_base.lua:2: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	../../skynet_fly/lualib/utils/net/ws_pbnet_util.lua:3: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.//lualib/hall/hall_plug.lua:54: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.../skynet_fly/lualib/module/room_game/room_game_hall_m.lua:451: in upvalue 'module_start'
> 	../../skynet_fly/service/hot_container.lua:110: in function 'room_game_hall_m.start'
> 	../../skynet_fly/lualib/utils/skynet_util.lua:40: in upvalue 'f'
> 	../../skynet_fly/skynet/lualib/skynet.lua:385: in function <../../skynet_fly/skynet/lualib/skynet.lua:357>
> stack traceback:
> 	[C]: in function 'error'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:99: in function 'skynet.require.require'
> 	(...tail calls...)
> 	../../skynet_fly/lualib/utils/net/ws_pbnet_util.lua:3: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.//lualib/hall/hall_plug.lua:54: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.../skynet_fly/lualib/module/room_game/room_game_hall_m.lua:451: in upvalue 'module_start'
> 	../../skynet_fly/service/hot_container.lua:110: in function 'room_game_hall_m.start'
> 	../../skynet_fly/lualib/utils/skynet_util.lua:40: in upvalue 'f'
> 	../../skynet_fly/skynet/lualib/skynet.lua:385: in function <../../skynet_fly/skynet/lualib/skynet.lua:357>
> stack traceback:
> 	[C]: in function 'error'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:99: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.//lualib/hall/hall_plug.lua:54: in upvalue 'modfunc'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:70: in function <../../skynet_fly/skynet/lualib/skynet/require.lua:69>
> 	[C]: in function 'xpcall'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:83: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.../skynet_fly/lualib/module/room_game/room_game_hall_m.lua:451: in upvalue 'module_start'
> 	../../skynet_fly/service/hot_container.lua:110: in function 'room_game_hall_m.start'
> 	../../skynet_fly/lualib/utils/skynet_util.lua:40: in upvalue 'f'
> 	../../skynet_fly/skynet/lualib/skynet.lua:385: in function <../../skynet_fly/skynet/lualib/skynet.lua:357>
> stack traceback:
> 	[C]: in function 'error'
> 	../../skynet_fly/skynet/lualib/skynet/require.lua:99: in function 'skynet.require.require'
> 	(...tail calls...)
> 	.../skynet_fly/lualib/module/room_game/room_game_hall_m.lua:451: in upvalue 'module_start'
> 	../../skynet_fly/service/hot_container.lua:110: in function 'room_game_hall_m.start'
> 	../../skynet_fly/lualib/utils/skynet_util.lua:40: in upvalue 'f'
> 	../../skynet_fly/skynet/lualib/skynet.lua:385: in function <../../skynet_fly/skynet/lualib/skynet.lua:357>
> stack traceback:
> 	[C]: in function 'assert'
> 	../../skynet_fly/skynet/lualib/skynet.lua:967: in function 'skynet.dispatch_message'
> [:0000000d][20231128 18:18:07 76][fatal][contriner_mgr][../../skynet_fly/service/contriner_mgr.lua:81]launch_new_module err  room_game_hall_m {
> 	net_util = ws_pbnet_util,
> 	hall_plug = hall_plug,
> }
>  
> [:00000011][20231128 18:18:07 76]LAUNCH snlua hot_container room_game_alloc_m 1 2023-11-28[18:18:07] 1701166687 1
> [:00000011][20231128 18:18:07 76]register_protocol:lua id:10
> [:00000011][20231128 18:18:07 76]register_protocol:response id:1
> [:00000011][20231128 18:18:07 76]register_protocol:error id:7
> [:00000011][20231128 18:18:07 76]register_protocol:debug id:9
> [:00000011][20231128 18:18:07 77]write_module_info: room_game_alloc_m
> [:00000012][20231128 18:18:07 77]LAUNCH snlua hot_container room_game_table_m 1 2023-11-28[18:18:07] 1701166687 1
> [:00000012][20231128 18:18:07 77]register_protocol:lua id:10
> [:00000012][20231128 18:18:07 77]register_protocol:response id:1
> [:00000012][20231128 18:18:07 77]register_protocol:error id:7
> [:00000012][20231128 18:18:07 77]register_protocol:debug id:9
> [:00000011][20231128 18:18:07 77]preready write: room_game_alloc_m.required
> 1111111111111111 name:	skynet.socketdriver	 m:	table: 0x7f9216326640	
> 
> [:00000012][20231128 18:18:07 78]skynet.register_protocol...
> [:00000012][20231128 18:18:07 78]register_protocol:socket id:6
> 1111111111111111 name:	skynet.socket	 m:	table: 0x7f9216326680	
> 
> 1111111111111111 name:	skynet.socket	 m:	table: 0x7f9216326680	
> 
> 1111111111111111 name:	skynet.socketdriver	 m:	table: 0x7f9216326640	
> 
> [:00000012][20231128 18:18:07 79]skynet.register_protocol...
> [:00000012][20231128 18:18:07 79]register_protocol:socket id:6
> [:00000012][20231128 18:18:07 79]lua call [d to :12 : 11 msgsz = 95] error : ../../skynet_fly/skynet/lualib/skynet.lua:967: ../../skynet_fly/skynet/lualib/skynet.lua:435: ../../skynet_fly/skynet/lualib/skynet/require.lua:99: ../../skynet_fly/skynet/lualib/skynet/require.lua:99: ../../skynet_fly/skynet/lualib/skynet/require.lua:99: ../../skynet_fly/skynet/lualib/skynet/require.lua:99: ../../skynet_fly/skynet/lualib/skynet.lua:54: assertion failed!
> stack traceback:
> 	[C]: in function 'assert'
> 	../../skynet_fly/skynet/lualib/skynet.lua:54: in function 'skynet.register_protocol'
> 	../../skynet_fly/skynet/lualib/skynet/socket.lua:218: in upvalue 'modfunc'
> 	



机器信息是：

> [root@beta-centos-1 game]# cat /etc/redhat-release
> CentOS Linux release 7.9.2009 (Core)
> [root@beta-centos-1 game]# uname -a
> Linux beta-centos-1 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> 

然后gcc版本是这样安装的：
```
sudo yum install centos-release-scl -y
sudo yum install devtoolset-8-gcc* -y
sudo scl enable devtoolset-8 bash
mv /usr/bin/gcc /usr/bin/gcc-4.8.5
ln -s /opt/rh/devtoolset-8/root/bin/gcc /usr/bin/gcc
mv /usr/bin/g++ /usr/bin/g++-4.8.5
ln -s /opt/rh/devtoolset-8/root/bin/g++ /usr/bin/g++
```

我打算用源码重新装一遍gcc，然后整理一个安装脚本出来。

**Comment by bluesky0521** [comment]
源码编译安装了gcc12，也还是不行

**Comment by huahua132** [comment]
我用虚拟机装了centos7.9 编译运行没有发现问题

**Comment by huahua132** [comment]
我在阿里云的机器上
直接用git clone 的skynet_fly
然后执行这些命令
![C_{F$UN`Q$OQZZ}0$)ZZAV5](https://github.com/huahua132/skynet_fly/assets/41766775/2f295cbf-a25b-4ada-96dc-a85753f1694a)
然后make cleanall
makebuild
cd examples/
cd digitalbomb/
 sh ../../binshell/make_server.sh ../../
sh script/restart.sh load_mods.lua
![RRQYAO4_L6{4W }TXGR_ZJP](https://github.com/huahua132/skynet_fly/assets/41766775/192f9f37-b3ce-47de-afea-6f1ae1fd7b6f)
启动没有报错

**Comment by bluesky0521** [comment]
我今天重新买了机器试了下，没有问题了...
