### ISSUE TITLE
Is it possible to use lua-radix-router to get the best performance?

### ISSUE THREAD

**Issue by vm-001** [huahua132/skynet_fly#21]
Hi @huahua132 . The [lua-radix-router](https://github.com/vm-001/lua-radix-router/pull/14) is optimized for high performance. Compared to the current router(based on redis rax), the lua-radix-router is 70x faster in real-world use cases. It is possible to switch lua-radix-router? I think the APIs are basically the same, it should be easy to replace without introducing any breaking changes.

**Comment by huahua132** [comment]
I need to compare before deciding whether to replace

**Comment by vm-001** [comment]
I made a PR here https://github.com/huahua132/skynet_fly/pull/22. Let me know if you have concerns.

**Comment by huahua132** [comment]
Thank you for your recommendation, I need to think about it carefully

**Comment by vm-001** [comment]
Take your time. Do you have test cases for the current router based on rax. I don't see GitHub workflow in this repo. I would like to run the test

**Comment by huahua132** [comment]
The test cases for rax are available here https://github.com/hanxi/lua-rax.
Introduction to the workflow of this project. Sorry, the English version is not available yet. You can take a look at the Chinese version introduction

**Comment by huahua132** [comment]
![image](https://github.com/huahua132/skynet_fly/assets/41766775/be80de8e-4785-4db1-a4b8-ef5c1d48517a)

**Comment by huahua132** [comment]
Already replaced, the test results are here https://huahua132.github.io/2024/01/14/skynet_fly/benchmark_rax/

**Comment by huahua132** [comment]
script is here https://github.com/huahua132/skynet_fly/blob/master/test/load_mods_radix_router.lua
You can run it like this
git clone https://github.com/huahua132/skynet_fly.git
make build
cd test
sh make.sh
sh sh script/restart.sh load_mods_radix_router.lua
vim logs/server.log

**Comment by huahua132** [comment]
Sorry, this suggestion cannot be adopted. The web is only one of the functions of the framework. The web also relies on many framework functions, so it is not easy to separate them independently.
