### ISSUE TITLE
在游戏中使用redisf会报错

### ISSUE THREAD

**Issue by bluesky0521** [huahua132/skynet_fly#5]
在skynet_fly_demo\games\crash\lualib\table\table_plug.lua中写入:
`local redisf = require "redisf"`
执行到skynet_fly_demo\skynet_fly\lualib\write_mod_required.lua这里会报错，无法生成skynet_fly_demo\games\crash\module_info\room_game_table_m.required：

> [:00000012][20231121 17:59:51 58]lua call [d to :12 : 11 msgsz = 72] error : ^[[31m../../skynet_fly/skynet/lualib/skynet.lua:966: ../../skynet_fly/skynet/lualib/skynet.lua:434: ../../skynet_fly/skynet/lualib/skynet/require.lua:96: ../../skynet_fly/skynet/lualib/skynet/require.lua:96: ../../skynet_fly/skynet/lualib/skynet/require.lua:36: module 'sha2' not found:
        no field package.preload['sha2']
        no file './sha2.lua'
        no file './/logs/sha2.lua'
        no file './/lualib/sha2.lua'
        no file './/lualib/alloc/sha2.lua'
        no file './/lualib/enum/sha2.lua'
        no file './/lualib/hall/sha2.lua'
        no file './/lualib/login/sha2.lua'
        no file './/lualib/module/sha2.lua'
        no file './/lualib/table/sha2.lua'
        no file './/module_info/sha2.lua'
        no file './/proto/sha2.lua'
        no file './/script/sha2.lua'
        no file '../../common/sha2.lua'
        no file '../../common//enum/sha2.lua'
        no file '../../common//msg/sha2.lua'
        no file '../../common//proto/sha2.lua'
        no file '../../skynet_fly/lualib/sha2.lua'
        no file '../../skynet_fly/lualib/cache/sha2.lua'
        no file '../../skynet_fly/lualib/check/sha2.lua'
        no file '../../skynet_fly/lualib/client/sha2.lua'

**Comment by huahua132** [comment]
谢谢，已解决 @bluesky0521 
[04ff2075a1fd90c22ad3d436294943a89283cf25](https://github.com/huahua132/skynet_fly/commit/04ff2075a1fd90c22ad3d436294943a89283cf25)
